export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_FAILED = "AUTHENTICATE_FAILED";
export const LOGOUT = "LOGOUT";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

export const FETCH_IMAGES = "FETCH_IMAGES";
export const UPLOADING = "UPLOADING";
export const DELETE_IMAGE = "DELETE_IMAGE";

export const FETCH_COLLECTION = "FETCH_COLLECTION";
export const ADD_COLLECTION = "ADD_COLLECTION";
export const REMOVE_COLLECTION = "REMOVE_COLLECTION";
export const EDIT_COLLECTION = "EDIT_COLLECTION";
export const UPDATE_COLLECTION = "UPDATE_COLLECTION";
